// <auto-generated />
using System;
using CursoWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CursoWebApi.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20180915150759_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("CursoWebApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PalavraChave")
                        .HasColumnName("Key")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new { Id = 1, Nome = "CSHARP", PalavraChave = "csharp" },
                        new { Id = 2, Nome = "VISUAL STUDIO 2017", PalavraChave = "visualstudio" },
                        new { Id = 3, Nome = "SQL SERVER", PalavraChave = "sqlserver" },
                        new { Id = 4, Nome = "ASP.NET CORE", PalavraChave = "aspnetcore" }
                    );
                });

            modelBuilder.Entity("CursoWebApi.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PostId");

                    b.Property<int?>("CategoriaId")
                        .HasColumnName("CategoriaId");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnName("Data")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnName("DescricaoPost")
                        .IsUnicode(false);

                    b.Property<string>("Titulo")
                        .HasColumnName("TituloPost")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.HasKey("PostId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("CursoWebApi.Models.Post", b =>
                {
                    b.HasOne("CursoWebApi.Models.Categoria", "Categoria")
                        .WithMany("Posts")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK__Post__CategoriaId");
                });
#pragma warning restore 612, 618
        }
    }
}
